-- sql
CREATE TABLE user_profiles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    created_at BIGINT,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

CREATE TABLE trainers
(
    id   BIGINT NOT NULL,
    bio  TEXT,
    phone VARCHAR(64),
    CONSTRAINT pk_trainers PRIMARY KEY (id),
    CONSTRAINT fk_trainers_profile FOREIGN KEY (id) REFERENCES user_profiles (id) ON DELETE CASCADE
);

CREATE TABLE security_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at BIGINT,
    email      VARCHAR(255),
    password   VARCHAR(255) NOT NULL,
    user_name  VARCHAR(255) NOT NULL,
    profile_id BIGINT,
    CONSTRAINT pk_security_users PRIMARY KEY (id),
    CONSTRAINT uq_security_users_username UNIQUE (user_name),
    CONSTRAINT fk_security_users_profile FOREIGN KEY (profile_id) REFERENCES user_profiles (id) ON DELETE SET NULL
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(64) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, roles),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES security_users (id) ON DELETE CASCADE
);

CREATE TABLE slots
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trainer_id BIGINT NOT NULL,
    start_time BIGINT NOT NULL,
    duration   BIGINT NOT NULL CHECK (duration > 0),
    capacity   INT NOT NULL CHECK (capacity >= 0),
    type       VARCHAR(255),
    canceled   BOOLEAN DEFAULT FALSE,
    created_by BIGINT,
    location   TEXT,
    reason     TEXT,
    end_time   BIGINT,
    CONSTRAINT pk_slots PRIMARY KEY (id),
    CONSTRAINT fk_slots_trainer FOREIGN KEY (trainer_id) REFERENCES trainers(id) ON DELETE CASCADE,
    CONSTRAINT fk_slots_created_by FOREIGN KEY (created_by) REFERENCES security_users(id) ON DELETE SET NULL
);

-- Helpful indexes
CREATE INDEX idx_security_users_email ON security_users (email);
CREATE INDEX idx_user_roles_role ON user_roles (roles);

CREATE INDEX idx_slots_trainer_id ON slots (trainer_id);
CREATE INDEX idx_slots_start_time ON slots (start_time);
