CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Mapped from @Id and GenerationType.IDENTITY
    created_at BIGINT,
    email      VARCHAR(255),
    first_name       VARCHAR(255),
    last_name       VARCHAR(255),
    password   VARCHAR(255),
    user_name  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255),
    CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

